name: CI
on: [push, pull_request]
jobs:
  test:
    name: PHPUnit (PHP ${{ matrix.php-versions }}) (${{ matrix.composer.name }} dependencies)
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.3', '7.4']
        composer:
          - {name: "lowest", flags: " --prefer-dist --prefer-lowest"}
          - {name: "stable", flags: " --prefer-dist --prefer-stable"}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-versions }}'
          extensions: mbstring,intl
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: PHPUnit
        run: composer test

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring,intl
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: PHPStan
        run: composer phpstan

  coding-style:
    name: Coding style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring,intl
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: PHP CS Fixer
        run: composer cs:lint
